utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

plateforme:
    resource: "@PlateformeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
